{% set name = "symmray" %}
{% set version = "0.3.1" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/symmray-{{ version }}.tar.gz
  sha256: 89029ea61e7b6645a75e9938d44bbe543c421e43d7d90e07fdd834016098c79f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - hatch-vcs
    - pip
  run:
    - python >={{ python_min }}
    - autoray
    - cotengra

test:
  imports:
    - symmray
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/jcmgray/symmray
  dev_url: https://github.com/jcmgray/symmray
  doc_url: https://symmray.readthedocs.io/
  summary: A minimal block sparse symmetric and fermionic tensor python library
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jcmgray
